---
all:
  children:
    proxmox:
      hosts:
        ultron:
          ansible_host: "{{ proxmox_api_host }}"
          ansible_user: root
        gamera:
          ansible_host: "{{ proxmox_api_host }}"
          ansible_user: root
    runner:
      hosts:
        pa-runner:
          ansible_host: "{{ runner_vm_ip }}"
          ansible_user: "{{ runner_bootstrap_user }}"
        pa-runner-cae:
          ansible_host: "{{ runner_vm_ip }}"
          ansible_user: "{{ runner_bootstrap_user }}"
    site_pdx:
      hosts:
        ultron:
        pa-runner:
    site_cae:
      hosts:
        gamera:
        pa-runner-cae:
